### PR TITLE
Remove CRLF in favour of LF

### PR DESCRIPTION
**Pull request by YTG1234**
CRLF is bad so I removed it, and only allowed it to be in `*.bat` files

### CODE REVIEW

**Comment by redcreeper14385** [comment]
Why does Carriage Returns need to be removed?

**Review by BoogieMonster1O1 — APPROVED** [review]
Could you clone this and check if there's any changes to be committed?
crlf should become lf and the `\r`s should get removed

**Comment by redcreeper14385** [comment]
Is this likely to cause issues with the code, also why is this a necessary change?

**Comment by BoogieMonster1O1** [comment]
carriage returns are bad. they're ugly

**Comment by redcreeper14385** [comment]
> Is this likely to cause issues with the code
?

**Comment by BoogieMonster1O1** [comment]
follow conventions. always commit unix style, but checkout 'whatever' style :tiny_potato:

**Comment by BoogieMonster1O1** [comment]
It can cause unnecessary delays in git

**Comment by BoogieMonster1O1** [comment]
and unnecessary mass changes of files

**Comment by redcreeper14385** [comment]
Right, if this won't cause any issues with the code, I'll approve the changes, I assume it only affects Git.

**Review by redcreeper14385 — APPROVED** [review]
Looks good.

**Comment by BoogieMonster1O1** [comment]
merge this please

**Comment by redcreeper14385** [comment]
I will ASAP.

**Comment by YTG1234** [comment]
Red Creeper please delete this message after you see it
```c
while (true) { printf("Voldemap Bad and Worst"); }
```

**Pull request merged**
